# Route zum Index der Class "AppController"
app_index:
  expression: '/'
  controller: 'App\Controller\AppController'
  method: 'index'
  request: 'get'

# Route zum Index der Class "AppController" mit Übergabe einer numerischen Variable
school_subject_show:
  expression: '/subject/([0-9]*)/show'
  controller: 'App\Controller\SchoolSubjectController'
  method: 'show'
  request: 'get'
