# Route zum Index der Class "AppController"
app_index:
  expression: '/'
  controller: 'App\Controller\AppController'
  method: 'index'
  request: 'get'

app_search:
  expression: '/'
  controller: 'App\Controller\AppController'
  method: 'search'
  request: 'post'

exam_index:
  expression: '/exams'
  controller: 'App\Controller\ExamController'
  method: 'index'
  request: 'get'

exam_list:
  expression: '/exams/([0-9]*)/list'
  controller: 'App\Controller\ExamController'
  method: 'list'
  request: 'get'

exam_show:
  expression: '/exams/show/([0-9]*)'
  controller: 'App\Controller\ExamController'
  method: 'show'
  request: 'get'

authentication_login:
  expression: '/login'
  controller: 'App\Controller\AuthenticationController'
  method: 'login'
  request: ['get','post']

authentication_logout:
  expression: '/logout'
  controller: 'App\Controller\AuthenticationController'
  method: 'logout'
  request: 'get'

authentication_register:
  expression: '/register'
  controller: 'App\Controller\AuthenticationController'
  method: 'register'
  request: ['get','post']

admin_index:
  expression: '/admin'
  controller: 'App\Controller\AdminController'
  method: 'index'
  request: 'get'

admin_exam_index:
  expression: '/admin/exam'
  controller: 'App\Controller\Admin\ExamCrudController'
  method: 'index'
  request: [ 'get','post' ]

admin_exam_show:
  expression: '/admin/exam/([0-9]*)/show'
  controller: 'App\Controller\Admin\ExamCrudController'
  method: 'show'
  request: [ 'get','post' ]

admin_role_index:
  expression: '/admin/role'
  controller: 'App\Controller\Admin\RoleCrudController'
  method: 'index'
  request: ['get','post']

admin_role_show:
  expression: '/admin/role/([0-9]*)/show'
  controller: 'App\Controller\Admin\RoleCrudController'
  method: 'show'
  request: ['get','post']

admin_role_new:
  expression: '/admin/role/new'
  controller: 'App\Controller\Admin\RoleCrudController'
  method: 'new'
  request: 'post'

admin_role_add_permission:
  expression: '/admin/role/add-permission'
  controller: 'App\Controller\Admin\RoleCrudController'
  method: 'addPermission'
  request: 'post'

admin_user_index:
  expression: '/admin/user'
  controller: 'App\Controller\Admin\UserCrudController'
  method: 'index'
  request: ['get','post']

admin_group_index:
  expression: '/admin/group'
  controller: 'App\Controller\Admin\UserGroupCrudController'
  method: 'index'
  request: ['get','post']

admin_group_new:
  expression: '/admin/group/new'
  controller: 'App\Controller\Admin\UserGroupCrudController'
  method: 'new'
  request: 'post'

admin_permission_index:
  expression: '/admin/permission'
  controller: 'App\Controller\Admin\RolePermissionCrudController'
  method: 'index'
  request: ['get','post']

admin_permission_new:
  expression: '/admin/permission/new/new'
  controller: 'App\Controller\Admin\RolePermissionCrudController'
  method: 'new'
  request: 'post'

admin_school_subject_index:
  expression: '/admin/school_subject'
  controller: 'App\Controller\Admin\SchoolSubjectCrudController'
  method: 'index'
  request: ['get','post']

admin_school_subject_new:
  expression: '/admin/school_subject/new'
  controller: 'App\Controller\Admin\SchoolSubjectCrudController'
  method: 'new'
  request: 'post'

admin_school_subject_type_index:
  expression: '/admin/school_subject_type'
  controller: 'App\Controller\Admin\SchoolSubjectTypeCrudController'
  method: 'index'
  request: ['get','post']

admin_school_subject_type_new:
  expression: '/admin/school_subject_type/new'
  controller: 'App\Controller\Admin\SchoolSubjectTypeCrudController'
  method: 'new'
  request: 'post'

admin_topic_index:
  expression: '/admin/topic'
  controller: 'App\Controller\Admin\TopicCrudController'
  method: 'index'
  request: ['get','post']

admin_topic_new:
  expression: '/admin/topic/new'
  controller: 'App\Controller\Admin\TopicCrudController'
  method: 'new'
  request: 'post'

admin_exam_status_index:
  expression: '/admin/exam_status'
  controller: 'App\Controller\Admin\ExamStatusCrudController'
  method: 'index'
  request: ['get','post']

admin_exam_status_new:
  expression: '/admin/exam_status/new'
  controller: 'App\Controller\Admin\ExamStatusCrudController'
  method: 'new'
  request: 'post'

admin_data_upload_index:
  expression: '/admin/data-upload'
  controller: 'App\Controller\Admin\DataImportController'
  method: 'index'
  request: ['get','post']

user_profile_index:
  expression: '/profile'
  controller: 'App\Controller\Profile\ProfileController'
  method: 'index'
  request: 'get'

user_profile_save_settings:
  expression: '/profile/settings/save'
  controller: 'App\Controller\Profile\ProfileController'
  method: 'saveSettings'
  request: 'post'

kq_claim_start:
  expression: '/key-question/claim/([0-9]*)/start'
  controller: 'App\Controller\Profile\KeyQuestionWorkflowController'
  method: 'claimKeyQuestion'
  request: 'get'

kq_copy_start:
  expression: '/key-question/copy/([0-9]*)/start'
  controller: 'App\Controller\Profile\KeyQuestionWorkflowController'
  method: 'copyKeyQuestion'
  request: 'get'

kq_new_start:
  expression: '/key-question/new/start'
  controller: 'App\Controller\Profile\KeyQuestionWorkflowController'
  method: 'newKeyQuestion'
  request: 'get'

kq_claim_transfer:
  expression: '/key-question/claim/transfer'
  controller: 'App\Controller\Profile\KeyQuestionWorkflowController'
  method: 'transferKeyQuestion'
  request: 'post'

kq_new_transfer:
  expression: '/key-question/new/transfer'
  controller: 'App\Controller\Profile\KeyQuestionWorkflowController'
  method: 'createKeyQuestion'
  request: 'post'