# Route zum Index der Class "AppController"
app_index:
  expression: '/'
  controller: 'App\Controller\AppController'
  method: 'index'
  request: 'get'

app_search:
  expression: '/'
  controller: 'App\Controller\AppController'
  method: 'search'
  request: 'post'

exam_index:
  expression: '/exams'
  controller: 'App\Controller\ExamController'
  method: 'index'
  request: 'get'

exam_list:
  expression: '/exams/([0-9]*)/list'
  controller: 'App\Controller\ExamController'
  method: 'list'
  request: 'get'

exam_show:
  expression: '/exams/show/([0-9]*)'
  controller: 'App\Controller\ExamController'
  method: 'show'
  request: 'get'

authentication_login:
  expression: '/login'
  controller: 'App\Controller\AuthenticationController'
  method: 'login'
  request: ['get','post']

authentication_logout:
  expression: '/logout'
  controller: 'App\Controller\AuthenticationController'
  method: 'logout'
  request: 'get'

authentication_register:
  expression: '/register'
  controller: 'App\Controller\AuthenticationController'
  method: 'register'
  request: ['get','post']

admin_index:
  expression: '/admin'
  controller: 'App\Controller\AdminController'
  method: 'index'
  request: 'get'

admin_role_index:
  expression: '/admin/role'
  controller: 'App\Controller\Admin\RoleCrudController'
  method: 'index'
  request: ['get','post']

admin_role_show:
  expression: '/admin/role/([0-9]*)/show'
  controller: 'App\Controller\Admin\RoleCrudController'
  method: 'show'
  request: ['get','post']

admin_role_new:
  expression: '/admin/role/new'
  controller: 'App\Controller\Admin\RoleCrudController'
  method: 'new'
  request: 'post'

admin_role_add_permission:
  expression: '/admin/role/add-permission'
  controller: 'App\Controller\Admin\RoleCrudController'
  method: 'addPermission'
  request: 'post'

admin_group_index:
  expression: '/admin/group'
  controller: 'App\Controller\Admin\UserGroupCrudController'
  method: 'index'
  request: ['get','post']

admin_group_new:
  expression: '/admin/group/new'
  controller: 'App\Controller\Admin\UserGroupCrudController'
  method: 'new'
  request: 'post'

admin_permission_index:
  expression: '/admin/permission'
  controller: 'App\Controller\Admin\RolePermissionCrudController'
  method: 'index'
  request: 'get'

admin_permission_new:
  expression: '/admin/permission/new'
  controller: 'App\Controller\Admin\RolePermissionCrudController'
  method: 'new'
  request: 'post'