# Route zum Index der Class "AppController"
app_index:
  expression: '/'
  controller: 'App\Controller\AppController'
  method: 'index'
  request: 'get'

app_search:
  expression: '/'
  controller: 'App\Controller\AppController'
  method: 'search'
  request: 'post'

exam_index:
  expression: '/exams'
  controller: 'App\Controller\ExamController'
  method: 'index'
  request: 'get'

exam_list:
  expression: '/exams/([0-9]*)/list'
  controller: 'App\Controller\ExamController'
  method: 'list'
  request: 'get'

exam_show:
  expression: '/exams/show/([0-9]*)'
  controller: 'App\Controller\ExamController'
  method: 'show'
  request: 'get'

authentication_login:
  expression: '/login'
  controller: 'App\Controller\AuthenticationController'
  method: 'login'
  request: ['get','post']